@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Director as dir
participant System

dir -> System : asks all resources
activate dir
activate System

System --> dir : requests project ID
deactivate System
dir -> System : inputs project ID
activate System
System --> dir : receives list of resources
@enduml