#!/bin/bash

#Este ficheiro tem de ser guardado na pasta cgi/bin do servidor

#/var/www/data/ ----> Este é o local onde vão ficar armazenados os ficheiros BASH gerados pelo scprit
#Antes de mais será necessário criar estas pastas no servidor
#cada objecto será um ficheiro
#Atributos de um objecto serao um path para outro objecto representado por um ficheiro
CREATEPROFILETYPE_STORE=/var/www/data/profiles


#Função de erro
error_response(){
echo "Status: 400 Bad Request"
echo "Content-type: text/plain"
echo ""
echo "ERROR: ${1}"
rm -f $M_CONTENT_FILE
exit
}

#Verifica se o request tem conteúdo.
if [ "$CONTENT_LENGTH" == "0" ]; then error_response "No body"; fi
cat > $M_CONTENT_FILE

#Verifica se o tipo de request é POST
if [ "$REQUEST_METHOD" != "POST" ]; then error_response "Invalid method. The only supported method is POST."; fi

#Verifica se a query-string não está vazia, pois queremos que esteja
if [ ! -z "$QUERY_STRING" ]; then error_response "Empty query string"; fi

#Criar content
CONTENT="$(cat $M_CONTENT_FILE)";

#Guardar a primeira variável
PROFILETYPE=$(echo $CONTENT | cut -d "_" -f 1 )
PROFILETYPE=${PROFILETYPE#profileType=}
PROFILETYPE=$(echo $PROFILETYPE | xargs)
if [ -z "$PROFILETYPE" ]; then error_response "empty profileType"; fi

#Guardar a segunda variável
DESCRIPTION=$(echo $CONTENT | cut -d "_" -f 2 )
DESCRIPTION=${DESCRIPTION#description=}
DESCRIPTION=$(echo $DESCRIPTION | xargs)
if [ -z "$DESCRIPTION" ]; then error_response "empty description"; fi

#Criar ficheiro type
FILENAME="$CREATEPROFILETYPE_STORE/$PROFILETYPE.$DESCRIPTION.txt"
ISFOUND="false"
for FILE in /var/www/data/profiles/*; do
  if [ "$FILE" == "$FILENAME" ]; then
    ISFOUND="true"
  fi
done
if [ "$ISFOUND" == "true" ]; then error_response "This profile type is already exists"; fi

#Criar ficheiro create profile type
echo '<?xml version="1.0"?>' > "$CREATEPROFILETYPE_STORE/$PROFILETYPE.txt"
echo "<holder>" >> "$CREATEPROFILETYPE_STORE/$PROFILETYPE.txt"
echo "<profileType>"$PROFILETYPE"</profileType>" >> "$CREATEPROFILETYPE_STORE/$PROFILETYPE.txt"
echo "<description>"$DESCRIPTION"</description>" >> "$CREATEPROFILETYPE_STORE/$PROFILETYPE.txt"
echo "</holder>" >> "$CREATEPROFILETYPE_STORE/$PROFILETYPE.txt"

#Enviar resposta http
rm -f $M_CONTENT_FILE;
echo "Content-type: text/plain"
echo ""
echo "Changes saved"