@startuml
'https://plantuml.com/use-case-diagram

actor Director

usecase (US012 - As Director,  I want to create a new project.)

:Director: -- (US012 - As Director,  I want to create a new project.)
@enduml