@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant " Routes" as routes

participant "Controllers" as ctl

participant "ApplicationServices" as appService
participant "Repositories" as repos
participant "DataModel" as datamodel
participant "JPARepositories" as jparepos
participant "Domain" as domain
participant "DTO" as mapper

[o--> routes : GET https://localhost:8080/projects
activate routes
routes -> ctl : getListOfAllProjects
activate ctl
ctl -> appService : getListOfAllProjects
activate appService
appService -> repos : findAll
activate repos
repos -> jparepos : findAll
activate jparepos
jparepos --> repos : projectsJPA
deactivate jparepos
repos -> datamodel : toDomain(projectsJPA)
activate datamodel
datamodel -> domain : createProjects
activate domain
domain --> datamodel : projects
deactivate domain
datamodel --> repos : projects
deactivate datamodel
repos --> appService : projects
deactivate repos
appService -> mapper : projectDTO
activate mapper
mapper --> appService : projectDTO
deactivate mapper
appService --> ctl : projectDTO
deactivate appService

ctl --> routes : new ResponseEntity(projectDTO, HTTPStatus.OK)
deactivate ctl
deactivate routes




@enduml