@startuml
'https://plantuml.com/class-diagram



Class Project #aliceblue;line:blue;line.dotted;text:blue
Class Sprint #aliceblue;line:blue;line.dotted;text:blue
Class ProjectStore #aliceblue;line:blue;line.dotted;text:blue

skinparam class {
BackgroundColor #white
ArrowColor #black
BorderColor #black
}

ProjectStore o-right-"*" Project :  a list of
Project "1" -right-> "0..* " Sprint :  is carried out in

Class  ProjectStore #white;line:black;line.dotted;text:black

Class  Project #white;line:black;line.dotted;text:black {
startDate : LocalDate
endDate : LocalDate
code : int
sprintDuration :int
}

Class Sprint #white;line:black;line.dotted;text:black {
number : int
startDate : LocalDate
endDate : LocalDate
}

@enduml