@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "period\n: Period" as period
participant " service\n: ServiceValidateResource" as serv
participant "resource\n:Resource" as res


 -> serv : validateRoleIsUniqueInPeriod(List<Resource> resources, period, Email email)
activate serv
serv -> period : startDate = getStartingDate() : LocalDate
activate period
deactivate period
serv -> period : endDate = getEndingDate() : LocalDate
activate period
deactivate period
loop !startDate.isAfter(endDate)

loop for each resource in listResource

serv ->res :isActive = isActiveInDate(startDate) : boolean
activate res
deactivate res
serv -> res : hasEmail = hasEmail(email): boolean
activate res
deactivate res

end loop
opt isActive && hasEmail
<-- serv : false
end opt
serv -> serv : startDate = startDate.plusDays(1)
end loop

<-- serv : true
deactivate serv
@enduml