@startuml
'https://plantuml.com/sequence-diagram

participant ": ResourceRepository" as repoResource
participant "IResourceJPARepository" as resourceJPARepo <<interface>>
participant "resourceJPA\n: ResourceJPA" as resourceJPA
participant ": ResourceDomainDataAssembler" as resourceAssembler
participant "resource\n: Resource" as resource


autonumber

[-> repoResource : save(Resource resource)
activate repoResource
repoResource -> resourceAssembler : toData(resource)
activate resourceAssembler
resourceAssembler --> resourceJPA** : resourceJPA

resourceAssembler--> repoResource : resourceJPA
deactivate resourceAssembler

repoResource ->resourceJPARepo: save(resourceJPA)
activate resourceJPARepo
resourceJPARepo --> repoResource : resourceJPA
deactivate resourceJPARepo
repoResource -> resourceAssembler : toDomain(resourceJPA)
activate resourceAssembler
resourceAssembler-->resource**
resourceAssembler-->repoResource : resource
deactivate resourceAssembler
[<-- repoResource : resource
deactivate repoResource

@enduml