@startuml
'https://plantuml.com/sequence-diagram

actor Director as Dir
participant System as Sys
autonumber

Dir -> Sys: Create new ProjectTypology
Sys --> Dir: Insert data
Dir -> Sys: Type data
Sys --> Dir: Project Typology created

@enduml