@startuml
'https://plantuml.com/sequence-diagram

actor ": Administrator" as Admin
participant ": InactivateAccountUI" as UI
participant ": InactivateAccountController" as Controller
participant ": ITCompany" as IT
participant "accountStore : AccountStore" as store
participant "account : Account" as account

autonumber

Admin -> UI: Request to inactivate account \n and indicate email
activate UI

UI -> Controller : inactivateAccount(email : String) : boolean
activate Controller

Controller -> IT : getAccountStore() : AccountStore
activate IT
IT --> Controller : accountStore
deactivate IT
Controller -> store : findAccountByEmail(email : String) : Account
activate store
store --> Controller : account
deactivate store


Controller -> account : inactivateAccount() : boolean
activate account
account --> Controller : true
deactivate account

Controller --> UI : true
deactivate Controller
UI --> Admin : Inform operation success
deactivate UI
@enduml